trigger:
  - main

pool:
  name: Practice VM Pool 14 May 2026

steps:
  - script: |
      cd $(Build.SourcesDirectory)
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pkill gunicorn || true
      nohup venv/bin/gunicorn --bind 0.0.0.0:5000 app:app > /tmp/gunicorn.log 2>&1 &
    displayName: 'Deploy Flask App'
